[package]
name = "nbterm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
lsp-types = "0.97.0"
ratatui = "0.29.0"
serde = "1.0.219"
serde_json = "1.0.140"
tower-lsp = "0.20.0"
tree-sitter = "0.25.4"
